language: python
sudo: false

env:
  - PATH="${PATH}:${HOME}/.local/bin"

install:
  - pip install --upgrade gsutil
  - bin/setup-ci-secrets $encrypted_5ba036e89377_key $encrypted_5ba036e89377_iv

script:
  - 'test "${TRAVIS_PULL_REQUEST}" = "true" || site/build-and-publish.sh'
